# Generated by Django 4.0.3 on 2023-03-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_alter_customername_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customername',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
    ]
